# Generated by Django 2.1.4 on 2019-03-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('href', models.URLField()),
                ('title', models.TextField()),
                ('nasa_id', models.CharField(max_length=100)),
                ('media_type', models.CharField(max_length=100)),
                ('center', models.CharField(max_length=300)),
                ('keywords', models.TextField()),
                ('description_508', models.CharField(max_length=100)),
                ('secondary_creator', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('album', models.TextField()),
                ('photographer', models.CharField(max_length=100)),
                ('preview', models.URLField()),
                ('orig', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hits', models.IntegerField()),
                ('href', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=1000)),
                ('center', models.CharField(max_length=1000)),
                ('keywords', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('nasa_id', models.CharField(max_length=300)),
                ('photographer', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=500)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
            ],
        ),
    ]
